marge/git.py
setup.py

These two things are enough to make `nix-env --install` work properly
but should be better in general.

Fix setup.py and call trailerfilter indirectly

---

README.md

The repo must have been renamed/moved - Fixed travis links

Fixing broken build badge links

---

README.md
marge/app.py
marge/bot.py
pinnedNixpkgs.nix
tests/test_job.py

Main use case is running multiple instances of marge with different flags for different projects on the same repo. Beyond that it's mostly handy for debugging.

Add `--project-regexp` flag

---

README.md
deploy.yml

This was from the discussion here:
https://github.com/smarkets/marge-bot/issues/19#issuecomment-316229780
There are many different ways of doing this in k8s... Helm may be better. I tend to like ktmpl in our org because we can just quickly template without a lot of boiler.

Add k8s templates

---

marge/approvals.py
marge/gitlab.py
tests/test_approvals.py
tests/test_gitlab.py

The `/projects/id/merge_requests/iid/approvals` endpoint is only available in the Enterprise Edition. On CE, we can instead pretend that there are no approvals left.
See #30.

Prevent calls to approvals endpoint on CE

---

README.md
marge/app.py

This is handy for example when configuring marge-bot to run using container orchestration.
Fixes #35

Provide env var version of all cmd line args

---

marge/app.py

This solves two issues:
1. Unnecessary ssh-key-xxxx files are created when a proper key file was given
2. The former files are never removed.
Notice that the second happens since `NamedTemporaryFile` needs the file
to be explicitly closed before deleting it.
Fixes #38

Better handling of temporary ssh-key files

---

README.md

Fixes #41, by inserting a literal non-breaking space as suggested by @glensc .

README.md: use nonbreaking space for " Marge Bot"

---

marge/job.py
marge/merge_request.py
tests/test_job.py

This is a very simple of dealing with #14: just refuse to merge stuff if auto-squash is enabled and we want to tag the final commit.
In the future, a better approach could be to edit the merge request  description and put the tags there (assuming that this then becomes the full commit message, would need to try the feature more).

Refuse to merge if auto-squash and tagged commits

---

README.md
marge/app.py
marge/bot.py
marge/interval.py
marge/job.py
tests/test_interval.py
tests/test_job.py

At the moment, it was hard-coded that marge would wait 15 minutes for CI to finish. Different teams have different needs, so now this parameter can be set with  `--max-ci-time-in-minutes`, which defaults to 15.
In doing so, this PR also refactors the handling of configuration parameters, so that we don't need to keep an ever-growing list of arguments in the Bot constructor. In the process, we remove the dependency of `MergeJob` on `Bot` and modify the `--embargo` parameter so that it can now receive all the embargo times separated by commas.

Make CI waiting time configurable (+ option refactoring)

---

marge/job.py
tests/test_job.py

These commits improve the messages that marge-bot will leave on a merge-request when a merge attempts succeeds, based on cases we've seen in the past. E.g. this fixes #32 and fixes #33.

Better handling of failures when trying to merge

---

marge/bot.py

I assume there may have been some confusion with the option as parsed with argparse and the attributes as part of MergeJobOptions.

Fix check for the reapprove merge job option

---

marge/commit.py
tests/test_commit.py

Otherwise this will error if the branch contains a '/'.

URL encode branch names

---

README.md
deploy.yml
marge/app.py
marge/job.py
tests/test_job.py

It will add a `Part-of: <PR_URL>` tag to every commit in the PR. However, if `--add-tested` is also specified, the top commit will be spared (since it would be redundant otherwise).
Fixes #25.

Add the --add-part-of option

---

dockerize.nix
marge/git.py
marge/job.py
marge/trailerfilter.py
tests/test_git.py

This closes #53 by doing three things:
1. Fixing the locale of the docker image to be UTF-8 aware
2. Making it so that marge-bot is hardcoded to treat everything as some ascii-superset (and processes git messages etc. at the bytes level)
3. Make marge-bot unassign herself before crashing (so when run in a restarting container/service a problematic MR does not block the whole queue)

Hardcode utf-8

---

marge/job.py
tests/test_job.py

Rather than waiting for CI to pass, just approve right away; this is more
convenient for transient errors such as flaky builds, and I see no obvious
downside.

Closes #53: reapprove immediately after push

---

README.md
marge/app.py
marge/bot.py
tests/test_app.py

Copies the same debug logging as `--project-regexp` when filtering. It makes use of the MRs web_url as it's easily identifiable.
This has been quite useful for the project I'm working on, since not only can CI last a long time, but we currently have two branches that are targetted for a high number of MRs. This has allowed us to run an instance of Marge for both of these branches, allowing for some fast and dirty parallelisation.

Add feature to restrict marge to a specific branch

---

marge/app.py
marge/job.py

Logs can very quickly get swamped with new HTTPS connection from requests and CI polling messages. I understand that in most use cases, CI likely won't last too long, but these two messages take up the majority of the logs.

Reduce logging in non-debug

---

marge/bot.py

The logic is: we want to sleep at least 30 secs after iterating over all
projects (both so that people have a chance to undo accidental assignments to
marge and to not poll like crazy when nothing is happening to the repo). If
there are many projects, the current system sleeps too long, though. Let's just
sleep one sec between each by default and then make up the difference to the 30s
afterwards.

Sleep even less between polling for MRs

---

marge/app.py
marge/git.py
marge/job.py
tests/test_app.py
tests/test_git.py
tests/test_job.py

Fixes #72.
Adds a `--use-merge-strategy` option. It will cause marge to use `git merge` instead of `git rebase` when updating the merge request branch. This option conflicts with `--add-tested`.
I struggled a bit trying to find correct generic terms englobing both merge and rebase. Depending on the context I used update and fuse. There may be better ones.

Add a merge strategy

---

marge/git.py
tests/test_git.py

Fixes occasional error where local refs conflict with changes on the
remote:
error: some local refs could not be updated; try running
'git remote prune origin' to remove any old, conflicting branches

Prune stale branches when fetching from remote

---

marge/job.py

Newer versions of gitlab seem to have a `locked` state,
seemingly associated to accepting with "merge when pipeline succeeds".
Fixes #79

Handle the new 'locked' merge request state

---

marge/git.py

This MR fixed exception when running marge-bot on Windows:
```
2018-02-27 22:05:54,045 INFO Running git clone --origin=origin git@gitlab.com:group/Project.git 'C:\Users\oredko\AppData\Local\Temp\tmpkimhsi82\tmpj21n0on9'
Traceback (most recent call last):
File "marge.app", line 3, in <module>
marge.app.main()
File "C:\Development\Git\marge-bot\marge\app.py", line 233, in main
marge_bot.start()
File "C:\Development\Git\marge-bot\marge\bot.py", line 39, in start
self._run(repo_manager)
File "C:\Development\Git\marge-bot\marge\bot.py", line 57, in _run
projects,
File "C:\Development\Git\marge-bot\marge\bot.py", line 95, in _process_projects
self._process_merge_requests(repo_manager, project, merge_requests)
File "C:\Development\Git\marge-bot\marge\bot.py", line 125, in _process_merge_requests …
```

Fix Python 3 encoding issue on Windows

---

marge/app.py
marge/job.py
tests/test_app.py
tests/test_job.py

Add option to wait for approvals to reset after pushing.
When using the "new commits remove all approvals" option in a project's settings, it is possible to run into a race condition post-rebase where the approvals haven't reset by the time we check. This results in the later attempt to merge reporting that there are not enough approvals.

Wait for approvals race

---

marge/job.py
tests/test_job.py

It's possible that the changes in an MR already exist in the target branch - whether this was merged in manually or someone else happened to have a similar idea. If this happens, when we rebase the MR on the target the commits will be dropped, essentially turning into a no-op. This causes the filter-branch to fail as it expects some revisions to be listed. Whilst this has the same end result, it's clearer if we explain exactly what the issue is.

Fail to merge if changes already exist in target

---

marge/git.py
marge/job.py
tests/test_git.py

Because it doesn't always exist. Instead, we use the target branch of the merge request, which exists by definition.
Fixes #88

Don't assume master exists when removing local branches

---

marge/job.py
marge/pipeline.py
tests/gitlab_api_mock.py
tests/test_job.py
tests/test_pipeline.py

The current implementation fetches the latest CI status for a particular sha. While a relatively rare circumstance, it's possible that at the point Marge-bot picks up an MR, another developer may have branched from the same commit and pushed to the repository. This new pipeline would be detected by Marge-bot, which could then be cancelled, causing Marge-bot to drop the MR stating "CI cancelled", while the CI for the correct branch will have passed.
This MR changes the CI status check to use the pipelines API, in order to filter status by ref (branch).
Commit.fetch_by_id() is no longer used after this change, I wasn't entirely sure whether I should remove that as part of this, leave it for a follow-up, or for you to decide what to do with it.

Get latest CI status of a commit filtered by branch

---

marge/app.py
tests/test_app.py

Achieves two things:
- can be used together (experimental was an exclusive option group)
- recognizes the fact that --batch is quite well tested now

Make --batch and --add-tested non-experimental.

---

marge/single_merge_job.py

It's useful to check that we are still able to merge the MR after it has
finished CI. Whilst we can check the error message afterwards, these are
not always clearer and we'd essentially be doing the same checks as
these anyway.
As an extra advantage, we also refuse to merge if someone has since
unassigned from Marge (something that people tend to do without
realising it has no effect after Marge has run it's preflight checks).

Check MR is mergeable before accepting MR

---

README.md

With the current command, I have the following error : 
```
$ docker run smarkets/marge-bot -v $(pwd):/configuration --config-file=/configuration/marge-bot-config.yaml
usage: marge.app [-h] [--config-file CONFIG_FILE]
(--auth-token TOKEN | --auth-token-file FILE) --gitlab-url
URL (--ssh-key KEY | --ssh-key-file FILE)
[--embargo INTERVAL[,..]] [--use-merge-strategy]
[--add-tested] [--batch] [--add-part-of] [--add-reviewers]
[--impersonate-approvers]
[--approval-reset-timeout APPROVAL_RESET_TIMEOUT]
[--project-regexp PROJECT_REGEXP] [--ci-timeout CI_TIMEOUT]
[--max-ci-time-in-minutes MAX_CI_TIME_IN_MINUTES]
[--git-timeout GIT_TIMEOUT] [--branch-regexp BRANCH_REGEXP]
[--debug]
marge.app: error: File not found: /configuration/marge-bot-config.yaml
```

Fix docker cmd to mount configuration

---

README.md
marge/app.py
marge/bot.py
marge/git.py
marge/store.py
tests/test_app.py
tests/test_git.py

Adds a new command line argument: --git-reference-repo
Specify a local copy of the git repo to speed up git clone times and
minimize load on the remote side. This is useful with large
repositories.

Allow reference repository in git clone

---

marge/branch.py
marge/job.py
tests/gitlab_api_mock.py
tests/test_batch_job.py
tests/test_job.py
tests/test_single_job.py

Fix a few issues, and increases the robustness of the tests by providing specs for mocks. Details are available in individual commit messages.

A few fixes + increased robustness of tests

---

marge/bot.py

In order to enable bot derived class to launch different kind of jobs.
For example I createsd a derived Bot class that manages Rebase jobs : that new bot can overload the _get_job method in order to launch the proper job (Rebase)

Job invocation isolated in a method

---

marge/project.py
marge/single_merge_job.py
tests/test_project.py
tests/test_single_job.py

Note that this doesn't use the discussions API, as it's a rather
convoluted process that doesn't work entirely as expected (the resolved
field doesn't appear to exist, for instance). Instead, we just check if
this setting is enabled at the project level, and if we haven't assumed
it's a different error then this is the most likely cause.
Closes: #64

Add appropriate error if unresolved discussions on merge request

---

marge/job.py
marge/merge_request.py
tests/test_approvals.py

Check all approvers against all commit authors, and ensure a commit
author hasn't approved their own MR.
Closes: #15

Ensure reviewer and commit author aren't the same

---

.travis.yml
Makefile
README.md

Push a new docker image with tag "master" for every new build on the
master branch. This gives users wishing to run with the latest
development changes an easy way to stay up to date.
Note: when a tag is created, Travis sets the $TRAVIS_BRANCH envvar to
the tag, rather than the branch, hence why we only use this variable
now.
Closes: #139.

Push a master-tagged image

---

README.md
marge/app.py
marge/bot.py
marge/merge_request.py
tests/test_app.py
tests/test_merge_request.py

Marge currently merges requests in ascending order of creation time.
The --merge-order='updated_at' flag can tell marge to merge in
ascending order of merge request update time.
An update includes an additional commit or comment on the merge request

Add an option to merge requests in order of oldest update time

---

.gitignore
marge/app.py
marge/bot.py
marge/gitlab.py
marge/job.py
marge/merge_request.py
marge/single_merge_job.py
tests/git_repo_mock.py
tests/gitlab_api_mock.py
tests/test_app.py
tests/test_job.py
tests/test_merge_request.py
tests/test_single_job.py

Here's an attempt to add support for GitLab's new "merge_request/rebase" endpoint (#157), which should enable using marge in public gitlab instances (#159). It is enabled with `--rebase-remotely` and conflicts with `--use-merge-strategy` and all the `add-xxx` options.
It works by performing the rebase locally but replacing the `git push --force` step by a call to [this endpoint](https://docs.gitlab.com/ee/api/merge_requests.html#rebase-a-merge-request).
Because the change happens inside `MergeJob.update_from_target_branch_and_push()`, it wouldn't have been picked  by the mocklab tests, where this method was being replaced by a mock. So I went down a bit of a rabbit hole at first and started by adding a mock of git, to fix this. The mock works by hooking into the `Repo.git()` method and …

Support rebasing through GitLab's api

---

marge/bot.py
marge/project.py
tests/test_project.py

If we're on an appropriate GitLab version, that is. GitLab doesn't return the right permissions for projects belonging to the user if the project is in a subgroup, and Marge is set as a member of the top-level group[1]. This is rather annoying as Marge will then complain that she doesn't have permissions for a project when she does.
A new field available in GitLab version >= 11.2 allows us to only fetch projects for which we have a certain access level. This returns the right projects even with nested groups, so we can prefer this method if it is available.
Fixes: #156

 Only fetch projects with min access level

---

.gitignore
Makefile
dockerize.nix
pinnedNixpkgs.nix
pinnedNixpkgs.src.json

`nixpkgs` is now pinned in `nix/sources.json`.

nix: delete pinnedNixpkgs.nix

---

marge/merge_request.py

After this pull request https://github.com/smarkets/marge-bot/pull/186/files
Single assigned gitlab merge request does not work anymore because the key `assignees` does not exist.
`assignees` was just introduced with 11.11 (https://docs.gitlab.com/ce/user/project/merge_requests/index.html#multiple-assignees-startert).
Now both worlds are supported.

Fix single assignee support

---

dockerize.nix

The docker image is a bit bloated, I do not think we need kitchen-sink
git nor full coreutils etc. These changes slim down the image to around
85 from 165MiB packed or about 280MiB from 500MiB unpacked.
Also did some minor reformatting.

Make the docker image smaller; cosmetics

---

README.md
marge/app.py
marge/bot.py
tests/test_app.py

Source branch regexp option added.
Answer https://github.com/smarkets/marge-bot/issues/205

source branch regexp added

---

marge/job.py
marge/pipeline.py
tests/test_job.py
tests/test_pipeline.py

... if possible.
Since we operate on merge requests this makes more sense, but the feature was only available from version 10.5.
It allows us to fetch all pipelines for a particular merge request, including detached ones, which would otherwise not be fetched due to a different `ref` format.
An annoyance of this route is that it doesn't allow ordering or sorting, which we use to determine the latest pipeline by. However it's very simple to just do this ourselves; the only downside is this is no longer
customizable, but nothing in the codebase appears to use this feature anyway.
The batch job tries cancel pipelines by their status, which we can't filter by for this route (unless we do it manually as well) so I've left that using the old method. This can mean some detached pipelines may …

Fetch pipelines by merge request instead of branch

---

marge/merge_request.py
tests/test_merge_request.py

According to the docs:
"Set to 0 or provide an empty value to unassign all assignees."[1]
So setting to `None` seems like it would work, although in practice it doesn't.
I've manually tested with `0` and it works fine.
[1] https://docs.gitlab.com/ee/api/merge_requests.html#update-mr
Fixes: #189

Fix unassign when author is marge

---

marge/merge_request.py
tests/test_merge_request.py
tests/test_single_job.py

To accept an MR and remove the source branch one has to set `should_remove_source_branch` like mention here:
https://docs.gitlab.com/ee/api/merge_requests.html#accept-mr
I also checked older versions (10.3). It was always `should`. Maybe in v3 it was different.

Update API for remove source branch on merge.

---

marge/job.py
marge/single_merge_job.py
tests/test_job.py

Fixes a few places where we should be checking the target project instead of the source project. As such, these issues only currently affect merge requests from forked projects.

Fork fixes

---

marge/merge_request.py
marge/single_merge_job.py
pylintrc
tests/gitlab_api_mock.py
tests/test_merge_request.py

If the option `Delete source branch when merge request is accepted.` is not checked, the branch will not be removed.

Only delete source branch if it was forced.

---

requirements_override.nix

Dependencies were downloading `setuptools-scm` and `pytest-runner` at build
time because `pypi2nix` does not capture `setup_requires`.

Fix sandboxed build

---

marge/merge_request.py
marge/single_merge_job.py
tests/test_merge_request.py
tests/test_single_job.py

Passing this value as True makes gitlab assume that the MR must have
a pipeline, which means if it's doesn't, then the MR will be denied.
Instead we should use the value of project.only_merge_if_pipeline_succeeds,
As this will mean the gitlab logic will be correct:
If the MR requires a pipeline to merge then we'll only merge if a pipeline
succeeds
If the MR doesn't needs a pipeline to succeed (i.e. has this setting on the
project off) then we won't pass the parameter and hence the merge will be allowed
Fixes issue #240

Pass the correct value for merge_when_pipeline_succeeds

---

README.md
marge/app.py
marge/batch_job.py
tests/test_batch_job.py

Previously when merging batches fast forwarding is enabled. This is
problematic when reverting changes that have been fast forwarded as
you then have to revert each individual commit.
This commit adds an argument to disable the fast forward merging of
batches.
Fixes #255

Add argument to disable fast forwarding of batch merges

---

marge/app.py
marge/job.py
tests/test_job.py

#256 introduced an error where the use use_no_ff_batches option was not passed into the
options correctly. Merge options are passed into the batch job class,
and use_no_ff_batches was not included in the merge options.
Thus creating the error:
AttributeError: 'MergeJobOptions' object has no attribute 'use_no_ff_batches'
This PR adds use_no_ff_batches to the merge options.

Pass use_no_ff_batches into merge options

---

.gitignore
marge/app.py
marge/approvals.py
marge/batch_job.py
marge/git.py
marge/job.py
marge/merge_request.py
marge/single_merge_job.py
pylintrc
tests/test_job.py

Previously, we applies the commits in individual MRs to the batch MR linearly, so the commits will be rewritten and the commit sha will not be the same one passed CI, which is not good.
To make the commits be exactly the same in the individual MRs and the batch MR, I added an option to allow using merge commits in batch MRs. It acts as a helper commit in the temp branch (the batch branch) which won't affect the final merge method (we usually use the fast forwarding merge).
Besides, updating (rebase master and apply trailers) each MR before we create the batch MR to avoid rewrite commits after.
- Add `--use-merge-commit-batches` option: Use merge commit when creating batches, so that the commits in the batch MR will be the same with in individual MRs.
- Add `--skip-ci-batches` option: Skip …

Improve batching: allow batch MRs use merge commits

---

marge/batch_job.py

fix(BatchMergeRequest): fixed a bug which prevented marge batch merging with fast forward commits
batch_mr_sha was not set when fast forward merging

Fixed a bug which prevented marge batch merging with fast forward commits

---

marge/job.py
marge/merge_request.py
marge/single_merge_job.py
tests/gitlab_api_mock.py

Closes #263 
This is a first go at a linear back-off to check whether an MR has `merge_status` set to `can_be_merged` (see the discussion on the #263).
This probably needs quite a bit more work, in particular I'm aware that I haven't made any changes to `marge/batch_job.py` or added any tests. I was a bit confused by how mocking is implemented, so I'd be grateful for some pointers if you'd like more tests.

Wait for merge status to resolve.

---

README.md

At some point GitLab renamed its user roles, and `Master` became `Maintainer`. This commit brings the marge-bot up to date with this change.

Rename Master role as Maintainer

---

README.md
marge/app.py
marge/bot.py
marge/merge_request.py
tests/test_app.py
tests/test_merge_request.py

Previously the option merge_order had two choices created_at and updated_at.
This is problematic in large projects as both options does not allow
the maintainer to control the order of merge requests.
This commit adds a new choice assigned_at to the option merge_order as
maintainers in large project often expect the order of the merge requests
related to order in which the merge requests did got assigned to the
marge-bot user.
Signed-off-by: Konrad Weihmann <konrad.weihmann@mbition.io>

Add new choice assigned_at to option merge_order

---

README.md
marge.app

While on it, also improve exception reporting for cases, where there're stdout and stderr set that should be printed, but they don't at the moment.
Fixes: #281

Mention in docs what determines a succeeded pipeline

---

marge/project.py

Valid access levels, according to:
https://docs.gitlab.com/ce/api/access_requests.html
are currently:
* No access (0)
* Minimal access (5) (Introduced in GitLab 13.5.)
* Guest (10)
* Reporter (20)
* Developer (30)
* Maintainer (40)
* Owner (50) - Only valid to set for groups
This commit ensures that the enum matches the docs.
This is a follow-up to PR #279 -- sorry I missed this one at the time!

AccessLevel enum matches GitLab docs

---

README.md
marge/app.py
marge/bot.py

This PR allows running marge-bot as a single job rather than looping indefinitely, so it can be managed via CI pipeline schedules instead of deploying it to your infrastructure.
See also renovate-bot's approach for something similar. https://docs.renovatebot.com/self-hosting/#gitlab-cicd-pipeline
I've added this as a simple flag since I wanted to keep codebase change to a minimum, although I was initially considering another `console_scripts` entrypoint. But I didn't want to change your approach to deployment too much (see also https://github.com/smarkets/marge-bot/issues/288) so I hope this is fine.
I also considered auto-detecting/defaulting to the `GITLAB_CI` and `CI_SERVER_URL` (for `gitlab_url`) env vars if marge detects it's in a CI environment, to get a bit closer to zero-config. …

Allow running marge-bot in CI pipelines or as a single CLI job

---

README.md
dockerize.nix
marge/app.py
marge/bot.py
marge/project.py
marge/store.py
tests/test_store.py

I finally found some time to implement this. I took @flaviouk idea and added a compatible argument parsing around it.
This is my first python project so I would love to get honest feedback, about parts that can be improved.
How do you like the idea of the mutally exclusive argument group of https vs. ssh?
Changes
* added configuration for HTTP(S) support
* added / configured cacerts nix package to allow SSL validation
* updated usage in Readme with latest `--help` output
* addded help section in Readme for configuring HTTP(S)

implement HTTPS support for cloning (#225)

---

README.md

I noticed some parameters were not formatted while reading the documentation.
This PR addresses this issue.

Consistent parameter formatting

---

marge/job.py
marge/merge_request.py
tests/gitlab_api_mock.py
tests/test_job.py

Resolves #317
Gives a nicer error message to the user if an MR cannot be merged due to unresolved discussions.

Report unresolved discussions to the user

---

marge/job.py
marge/project.py
tests/test_project.py

Use default branch instead of master

---

marge/job.py

When the bot is waiting for "merge when pipeline suceeds"
the hardcoded 5 minute timeout was applied.
We need to wait for CI to finish in this case,
so setting the merge timeout to CI timeout.

Use ci_timeout for merging
